version: '3.9'

services:
  postgres:
    image: postgres:16.2-alpine3.19
    container_name: db-picpay-clone
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=picpay
    ports:
      - '5432:5432'
    volumes:
      - 'picpay-db:/var/lib/postgresql/data'
  redis:
    image: redis:7.2.4-alpine3.19
    command: redis-server --loglevel warning --requirepass admin
    ports:
      - "6379:6379"

volumes:
  picpay-db:
