spring:
  application:
    name: picpayclone
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/picpay
    username: admin
    password: admin
    initialization-mode: always
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    format_sql: true
  api:
    version: 1.0.0

picpayclone:
  jwt:
    expiration: 86400000
    secret: YmYzYzgxMzI4YjlmZjJkN2ZiMTJjMjdmMmVmMjQ1ZjYwMDViNzhlZmQwOTdiZTY1Zjk4ZjY0ODc1NGQzZGU2NWM3MmNmMTNiZDIyZjk2ZjgyNzIzZTU2ZDgwZDRiYWVlNmYyNzdlZmNjZWQzMGJjMDE2NGQ3NzYyODA4YzM3OTY5NTY4MDNmZGJhNDBhOWQ2ZTVkMzk2ZDM3MjhmZDgzMjlkNGMyNThlZmQ0YjI5MWIzODA1YzdlNzhkNzk2Njcw
